//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Root
{

    private RootSettings settingsField;

    private RootCommonCard commonCardField;

    /// <remarks/>
    public RootSettings Settings
    {
        get
        {
            return this.settingsField;
        }
        set
        {
            this.settingsField = value;
        }
    }

    /// <remarks/>
    public RootCommonCard CommonCard
    {
        get
        {
            return this.commonCardField;
        }
        set
        {
            this.commonCardField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootSettings
{

    private string currencyField;

    private byte isCountryRussiaField;

    private byte withDescField;

    private byte withPrivelField;

    private byte expandedField;

    private byte headingExpandField;

    private string langField;

    private byte isWebField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte isCountryRussia
    {
        get
        {
            return this.isCountryRussiaField;
        }
        set
        {
            this.isCountryRussiaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte withDesc
    {
        get
        {
            return this.withDescField;
        }
        set
        {
            this.withDescField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte withPrivel
    {
        get
        {
            return this.withPrivelField;
        }
        set
        {
            this.withPrivelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte expanded
    {
        get
        {
            return this.expandedField;
        }
        set
        {
            this.expandedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte headingExpand
    {
        get
        {
            return this.headingExpandField;
        }
        set
        {
            this.headingExpandField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lang
    {
        get
        {
            return this.langField;
        }
        set
        {
            this.langField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte isWeb
    {
        get
        {
            return this.isWebField;
        }
        set
        {
            this.isWebField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCard
{

    private RootCommonCardClientInfo clientInfoField;

    private RootCommonCardCommonCardData commonCardDataField;

    /// <remarks/>
    public RootCommonCardClientInfo ClientInfo
    {
        get
        {
            return this.clientInfoField;
        }
        set
        {
            this.clientInfoField = value;
        }
    }

    /// <remarks/>
    public RootCommonCardCommonCardData CommonCardData
    {
        get
        {
            return this.commonCardDataField;
        }
        set
        {
            this.commonCardDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardClientInfo
{

    private RootCommonCardClientInfoCounters countersField;

    private RootCommonCardClientInfoParam[] clientParamsField;

    private RootCommonCardClientInfoPrivilege[] privilegesField;

    private RootCommonCardClientInfoCurrentSaldo currentSaldoField;

    private RootCommonCardClientInfoClientNote clientNoteField;

    private ushort abcodeField;

    private string fioField;

    private string addressField;

    private byte peopleField;

    private byte commonsquareField;

    private ulong phoneField;

    /// <remarks/>
    public RootCommonCardClientInfoCounters Counters
    {
        get
        {
            return this.countersField;
        }
        set
        {
            this.countersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Param", IsNullable = false)]
    public RootCommonCardClientInfoParam[] ClientParams
    {
        get
        {
            return this.clientParamsField;
        }
        set
        {
            this.clientParamsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Privilege", IsNullable = false)]
    public RootCommonCardClientInfoPrivilege[] Privileges
    {
        get
        {
            return this.privilegesField;
        }
        set
        {
            this.privilegesField = value;
        }
    }

    /// <remarks/>
    public RootCommonCardClientInfoCurrentSaldo CurrentSaldo
    {
        get
        {
            return this.currentSaldoField;
        }
        set
        {
            this.currentSaldoField = value;
        }
    }

    /// <remarks/>
    public RootCommonCardClientInfoClientNote ClientNote
    {
        get
        {
            return this.clientNoteField;
        }
        set
        {
            this.clientNoteField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort abcode
    {
        get
        {
            return this.abcodeField;
        }
        set
        {
            this.abcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fio
    {
        get
        {
            return this.fioField;
        }
        set
        {
            this.fioField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte people
    {
        get
        {
            return this.peopleField;
        }
        set
        {
            this.peopleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte commonsquare
    {
        get
        {
            return this.commonsquareField;
        }
        set
        {
            this.commonsquareField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardClientInfoCounters
{

    private RootCommonCardClientInfoCountersCounter counterField;

    /// <remarks/>
    public RootCommonCardClientInfoCountersCounter Counter
    {
        get
        {
            return this.counterField;
        }
        set
        {
            this.counterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardClientInfoCountersCounter
{

    private string serviceNameField;

    private string topologyNameField;

    private uint numberField;

    private string modelField;

    private string dateMountField;

    private string dateNextGospField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serviceName
    {
        get
        {
            return this.serviceNameField;
        }
        set
        {
            this.serviceNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string topologyName
    {
        get
        {
            return this.topologyNameField;
        }
        set
        {
            this.topologyNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string model
    {
        get
        {
            return this.modelField;
        }
        set
        {
            this.modelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dateMount
    {
        get
        {
            return this.dateMountField;
        }
        set
        {
            this.dateMountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dateNextGosp
    {
        get
        {
            return this.dateNextGospField;
        }
        set
        {
            this.dateNextGospField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardClientInfoParam
{

    private string nameField;

    private string valueField;

    private string dateBeginField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dateBegin
    {
        get
        {
            return this.dateBeginField;
        }
        set
        {
            this.dateBeginField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardClientInfoPrivilege
{

    private string nameField;

    private byte percentField;

    private byte countField;

    private string dateBeginField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte percent
    {
        get
        {
            return this.percentField;
        }
        set
        {
            this.percentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dateBegin
    {
        get
        {
            return this.dateBeginField;
        }
        set
        {
            this.dateBeginField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardClientInfoCurrentSaldo
{

    private decimal sumSaldoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal sumSaldo
    {
        get
        {
            return this.sumSaldoField;
        }
        set
        {
            this.sumSaldoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardClientInfoClientNote
{

    private string textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardData
{

    private RootCommonCardCommonCardDataYear[] commonCardYearsField;

    private RootCommonCardCommonCardDataBeginingSaldo beginingSaldoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Year", IsNullable = false)]
    public RootCommonCardCommonCardDataYear[] CommonCardYears
    {
        get
        {
            return this.commonCardYearsField;
        }
        set
        {
            this.commonCardYearsField = value;
        }
    }

    /// <remarks/>
    public RootCommonCardCommonCardDataBeginingSaldo BeginingSaldo
    {
        get
        {
            return this.beginingSaldoField;
        }
        set
        {
            this.beginingSaldoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYear
{

    private RootCommonCardCommonCardDataYearMonth[] monthField;

    private ushort numberField;

    private decimal feeSumField;

    private decimal paySumField;

    private byte payCntField;

    private decimal saldoSumField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Month")]
    public RootCommonCardCommonCardDataYearMonth[] Month
    {
        get
        {
            return this.monthField;
        }
        set
        {
            this.monthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal feeSum
    {
        get
        {
            return this.feeSumField;
        }
        set
        {
            this.feeSumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal paySum
    {
        get
        {
            return this.paySumField;
        }
        set
        {
            this.paySumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte payCnt
    {
        get
        {
            return this.payCntField;
        }
        set
        {
            this.payCntField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal saldoSum
    {
        get
        {
            return this.saldoSumField;
        }
        set
        {
            this.saldoSumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonth
{

    private RootCommonCardCommonCardDataYearMonthService[] serviceField;

    private RootCommonCardCommonCardDataYearMonthEvent[] eventsField;

    private string nameField;

    private byte numberField;

    private decimal paySumField;

    private bool paySumFieldSpecified;

    private byte payCntField;

    private bool payCntFieldSpecified;

    private decimal saldoSumField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Service")]
    public RootCommonCardCommonCardDataYearMonthService[] Service
    {
        get
        {
            return this.serviceField;
        }
        set
        {
            this.serviceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Event", IsNullable = false)]
    public RootCommonCardCommonCardDataYearMonthEvent[] Events
    {
        get
        {
            return this.eventsField;
        }
        set
        {
            this.eventsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal paySum
    {
        get
        {
            return this.paySumField;
        }
        set
        {
            this.paySumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool paySumSpecified
    {
        get
        {
            return this.paySumFieldSpecified;
        }
        set
        {
            this.paySumFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte payCnt
    {
        get
        {
            return this.payCntField;
        }
        set
        {
            this.payCntField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool payCntSpecified
    {
        get
        {
            return this.payCntFieldSpecified;
        }
        set
        {
            this.payCntFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal saldoSum
    {
        get
        {
            return this.saldoSumField;
        }
        set
        {
            this.saldoSumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthService
{

    private RootCommonCardCommonCardDataYearMonthServiceTypeuse typeuseField;

    private string nameField;

    private string unitField;

    private decimal feeSumField;

    private decimal feeValueField;

    private decimal privValueField;

    private bool privValueFieldSpecified;

    private string spiField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthServiceTypeuse Typeuse
    {
        get
        {
            return this.typeuseField;
        }
        set
        {
            this.typeuseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal feeSum
    {
        get
        {
            return this.feeSumField;
        }
        set
        {
            this.feeSumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal feeValue
    {
        get
        {
            return this.feeValueField;
        }
        set
        {
            this.feeValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal privValue
    {
        get
        {
            return this.privValueField;
        }
        set
        {
            this.privValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool privValueSpecified
    {
        get
        {
            return this.privValueFieldSpecified;
        }
        set
        {
            this.privValueFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string spi
    {
        get
        {
            return this.spiField;
        }
        set
        {
            this.spiField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthServiceTypeuse
{

    private RootCommonCardCommonCardDataYearMonthServiceTypeuseTop topField;

    private string nameField;

    private decimal feeValueField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthServiceTypeuseTop Top
    {
        get
        {
            return this.topField;
        }
        set
        {
            this.topField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal feeValue
    {
        get
        {
            return this.feeValueField;
        }
        set
        {
            this.feeValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthServiceTypeuseTop
{

    private RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriod[] periodField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Period")]
    public RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriod[] Period
    {
        get
        {
            return this.periodField;
        }
        set
        {
            this.periodField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriod
{

    private RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScale scaleField;

    private string nameField;

    private decimal beginField;

    private decimal endField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScale Scale
    {
        get
        {
            return this.scaleField;
        }
        set
        {
            this.scaleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal begin
    {
        get
        {
            return this.beginField;
        }
        set
        {
            this.beginField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal end
    {
        get
        {
            return this.endField;
        }
        set
        {
            this.endField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScale
{

    private RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleReadingBeg readingBegField;

    private RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleReadingEnd readingEndField;

    private RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleTariffs tariffsField;

    private string nameField;

    private byte zoneHeadIdField;

    private byte scaleIndexField;

    private string siField;

    private decimal feeValueField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleReadingBeg ReadingBeg
    {
        get
        {
            return this.readingBegField;
        }
        set
        {
            this.readingBegField = value;
        }
    }

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleReadingEnd ReadingEnd
    {
        get
        {
            return this.readingEndField;
        }
        set
        {
            this.readingEndField = value;
        }
    }

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleTariffs Tariffs
    {
        get
        {
            return this.tariffsField;
        }
        set
        {
            this.tariffsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte zoneHeadId
    {
        get
        {
            return this.zoneHeadIdField;
        }
        set
        {
            this.zoneHeadIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte scaleIndex
    {
        get
        {
            return this.scaleIndexField;
        }
        set
        {
            this.scaleIndexField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string si
    {
        get
        {
            return this.siField;
        }
        set
        {
            this.siField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal feeValue
    {
        get
        {
            return this.feeValueField;
        }
        set
        {
            this.feeValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleReadingBeg
{

    private byte typeField;

    private decimal valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleReadingEnd
{

    private byte typeField;

    private decimal valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleTariffs
{

    private RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleTariffsItem itemField;

    private bool isStepField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleTariffsItem Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isStep
    {
        get
        {
            return this.isStepField;
        }
        set
        {
            this.isStepField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthServiceTypeuseTopPeriodScaleTariffsItem
{

    private decimal feeValueField;

    private decimal tariffField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal feeValue
    {
        get
        {
            return this.feeValueField;
        }
        set
        {
            this.feeValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal tariff
    {
        get
        {
            return this.tariffField;
        }
        set
        {
            this.tariffField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthEvent
{

    private RootCommonCardCommonCardDataYearMonthEventUnMountCounter unMountCounterField;

    private RootCommonCardCommonCardDataYearMonthEventMountCounter mountCounterField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthEventUnMountCounter UnMountCounter
    {
        get
        {
            return this.unMountCounterField;
        }
        set
        {
            this.unMountCounterField = value;
        }
    }

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthEventMountCounter MountCounter
    {
        get
        {
            return this.mountCounterField;
        }
        set
        {
            this.mountCounterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthEventUnMountCounter
{

    private RootCommonCardCommonCardDataYearMonthEventUnMountCounterReading readingField;

    private string dateField;

    private ulong counterNumberField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthEventUnMountCounterReading Reading
    {
        get
        {
            return this.readingField;
        }
        set
        {
            this.readingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong counterNumber
    {
        get
        {
            return this.counterNumberField;
        }
        set
        {
            this.counterNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthEventUnMountCounterReading
{

    private RootCommonCardCommonCardDataYearMonthEventUnMountCounterReadingScale scaleField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthEventUnMountCounterReadingScale Scale
    {
        get
        {
            return this.scaleField;
        }
        set
        {
            this.scaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthEventUnMountCounterReadingScale
{

    private ushort valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthEventMountCounter
{

    private RootCommonCardCommonCardDataYearMonthEventMountCounterReading readingField;

    private string dateField;

    private ulong counterNumberField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthEventMountCounterReading Reading
    {
        get
        {
            return this.readingField;
        }
        set
        {
            this.readingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong counterNumber
    {
        get
        {
            return this.counterNumberField;
        }
        set
        {
            this.counterNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthEventMountCounterReading
{

    private RootCommonCardCommonCardDataYearMonthEventMountCounterReadingScale scaleField;

    /// <remarks/>
    public RootCommonCardCommonCardDataYearMonthEventMountCounterReadingScale Scale
    {
        get
        {
            return this.scaleField;
        }
        set
        {
            this.scaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataYearMonthEventMountCounterReadingScale
{

    private byte valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RootCommonCardCommonCardDataBeginingSaldo
{

    private decimal sumField;

    private string dateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal sum
    {
        get
        {
            return this.sumField;
        }
        set
        {
            this.sumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }
}
